### ISSUE TITLE
Replacements / help for deprected functions

### ISSUE THREAD

**Issue by adomingues** [alanocallaghan/scater#101]
Dear all,

We have some workflows developed with `scater v1.10.1` which I was testing with `1.14.6`. I noticed that many functions have been deprecated or completely removed, and though most of them seem to have replaced there is one I am struggling with.

In the past `calculateQCMetrics` populated the `rowData` and and `colData` with all sorts of statistics. Currently `scater::perCellQCMetrics(sce)` appears to generate most of per cell data, however, `perFeatureQCMetrics`  only generates the variables `mean` and `detected` as opposed to  the much more comprehensive summary of old (from `.get_qc_metrics_per_gene`): `mean_counts`, ` log10_mean_counts`, `rank_counts`, `n_cells_counts`, `pct_dropout_counts`, `total_counts`, `log10_total_counts` .

Of course all of this is possible re-create manually, but I wonder if you have any plans to add this to `perFeatureQCMetrics`?

Cheers.

**Comment by LTLA** [comment]
There are several reasons why I removed those additional variables.

Firstly, as you may notice, almost all of the removed variables are highly redundant with each other. For example, `log10_mean_counts` is simply `log10(mean_counts)`, `total_counts` is simply `mean_counts * <number of cells>`, and `rank_counts` is simply `rank(mean_counts)`. I didn't want to pollute the `rowData()` with loads of redundant stuff, so I stripped it down.

Of these, the `total_counts` and `n_cells_counts` are more or less useless for diagnostic purposes, because you can't interpret them without knowing the total number of cells. For example, if I told you that 200 cells express a gene, the next question you would ask is "of how many cells  in total?" The means and percentages were really the only relevant QC measure here, which is what is reported by `mean` and `detected`, respectively.

I guess the log-mean might be useful, but in the plots I've been making (when I do make them), I plot the raw mean and then throw in a `scale_x_log10()`. And typing `log10(mean)` is about the same number of characters as `log10_mean_counts` anyway, so I didn't feel it was that big a deal.

Finally, I have no idea what the rank mean was meant to tell people w.r.t. their data quality. But again, `rank(mean)` is about the same number of characters as `rank_mean_count`, so...

I think you're the first person who's told me that they actually use `perFeatureQCMetrics`. I haven't bothered to look at per-gene metrics for a long time in my own workflows, so I don't know what people are using it for. Are you sure you need all of that extra stuff?

**Comment by adomingues** [comment]
thank you for the detailed explanation Aaron.

> I think you're the first person who's told me that they actually use perFeatureQCMetrics. 

As far as I can tell, we are only using  `plotExprsFreqVsMean` which is now defunct. It was only when I started working on a alternative to it that I noticed the missing variables (and different variable names) and got curious. 

> Are you sure you need all of that extra stuff?

After you explanation I don't think so. The only wrapper function I need is alternative to:

```R
scater::plotExprsFreqVsMean(sce)
Error in .qc_hunter(object, paste0("n_cells_by_", exprs_values), mode = "row") : 
  failed to find 'n_cells_by_counts' in row metadata
In addition: Warning message:
'scater::plotExprsFreqVsMean' is deprecated.
Use 'plotRowData' instead.
See help("Deprecated") 
```
which I guess is now:

```R
rowData(sce) <- cbind(
  rowData(sce),
  get_qc_metrics_per_gene(assay(sce, exprs_values = "counts"))
)
## define percentage of cells expressing a gene
scater::plotRowData(sce, x = "detected", y = "mean")
```

Is this correct? If so, the issue is solved. 

Cheers,
António

**Comment by LTLA** [comment]
I don't know where you got `get_qc_metrics_per_gene` from, but you can just use `addPerFeatureQC` to add per-feature QC metrics to the `rowData` of the SCE. Otherwise it looks fine.

**Comment by adomingues** [comment]
Excellent, thank you. 

> I don't know where you got get_qc_metrics_per_gene from

Sorry, I had renamed `.get_qc_metrics_per_feature` (taken from [here](https://github.com/davismcc/scater/blob/RELEASE_3_7/R/calculateQCMetrics.R#L387)) in my test code

**Comment by Anna-RNA88** [comment]
> There are several reasons why I removed those additional variables.
> 
> Firstly, as you may notice, almost all of the removed variables are highly redundant with each other. For example, `log10_mean_counts` is simply `log10(mean_counts)`, `total_counts` is simply `mean_counts * <number of cells>`, and `rank_counts` is simply `rank(mean_counts)`. I didn't want to pollute the `rowData()` with loads of redundant stuff, so I stripped it down.
> 
> Of these, the `total_counts` and `n_cells_counts` are more or less useless for diagnostic purposes, because you can't interpret them without knowing the total number of cells. For example, if I told you that 200 cells express a gene, the next question you would ask is "of how many cells in total?" The means and percentages were really the only relevant QC measure here, which is what is reported by `mean` and `detected`, respectively.
> 
> I guess the log-mean might be useful, but in the plots I've been making (when I do make them), I plot the raw mean and then throw in a `scale_x_log10()`. And typing `log10(mean)` is about the same number of characters as `log10_mean_counts` anyway, so I didn't feel it was that big a deal.
> 
> Finally, I have no idea what the rank mean was meant to tell people w.r.t. their data quality. But again, `rank(mean)` is about the same number of characters as `rank_mean_count`, so...
> 
> I think you're the first person who's told me that they actually use `perFeatureQCMetrics`. I haven't bothered to look at per-gene metrics for a long time in my own workflows, so I don't know what people are using it for. Are you sure you need all of that extra stuff?

Hi Aaron, I am a fresh learner in bioinformatics. I am struggling to follow a tutorial from Sanger institute (from July 2019) on analysis of single cell RNA Seq data. In the tutorial, calculateQCMetrics was employed, which can antomatically generate "is_feature_control" for the following data overview and data visualization. Now because calculateQCMetrics() metrics function is depreciated, I would like to inquire how to generate the "is_feature_control" ? Could you provide some codes to help me figure out this frustrating problems. Thank you very much! 
Anna

**Comment by LTLA** [comment]
Open a new issue or post your question on support.bioconductor.org, it's hard to keep track of closed issues.

**Comment by Anna-RNA88** [comment]
> Open a new issue or post your question on support.bioconductor.org, it's hard to keep track of closed issues.
Okay. Thanks for your reminder!

**Comment by Anna-RNA88** [comment]
Dear Aaron,

Thanks for your email and reminder.
I have already opened a new issue a few minutes ago. Please have a look.

Looking forward to your reply and help.
Thanks!

Best regards,
Anna

________________________________
