### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by lmweber** [alanocallaghan/scater#110]
Hi, I was just re-installing all my packages for R version 4.0.0, and had a minor suggestion regarding dependencies -- I think it would be good to include packages such as `Rtsne` and `uwot` under `Imports` instead of `Suggests`, so that functions like `plotReducedDim` work out of the box.

Currently these packages need to be installed separately, and `plotReducedDim` returns errors if the packages are not available, which could be confusing for beginners. If they are under `Imports` I believe they would be installed automatically when installing `scater`.

This is probably also the case for several other packages under `Suggests`, although I haven't gone through them all to check.

**Comment by LTLA** [comment]
The problem with putting them all in `Imports:` is that they get dragged in whenever **scater** is loaded. This is unacceptable for all downstream packages that depend on **scater**. For example, **scran** doesn't use or care about **scater**'s visualization-related code, and it would not appreciate an increase in its dependency count courtesy of **scater** moving those packages into `Imports:`.

The real problem is that **scater** is a dependency of **scran** and co. at all. This reflects an unfortunate conflation between **scater**'s visualization code and all its other useful bits and pieces. I am planning to divorce those two parts into separate components in the next release, at which point **scater** is free to gorge on an unhealthy number of dependencies without ruining everyone else.

**Comment by lmweber** [comment]
I thought putting them in `Imports:` would only add them as dependency packages for installation, not also for loading? If I understand it correctly, they would only be dependencies for loading (with `library`) if they are in `Depends:`.

But yes even for installation dependencies, I agree. Adding them in `Imports:` would in turn make them dependencies of `scran`, which inflates the dependency count of `scran`. Best to keep dependency counts minimal wherever possible. Thanks for the reply.

**Comment by LTLA** [comment]
Both `Depends:` and `Imports:` packages are loaded but only `Depends:` packages are attached to the global search path. I suspect the loading overhead is not too bad, I think it's all done lazily anyway; it's the installation step that is rendered fragile by inclusion of more dependencies.
