### ISSUE TITLE
scale_fill_*() ignored by plotExpression() if shape_by argument present

### ISSUE THREAD

**Issue by ceiron61** [alanocallaghan/scater#122]
I noticed the following behaviour in `scater 1.1.6.2` (current Bioconductor "release" version) when using `plotExpression()` in conjunction with one of the `scale_fill_*()` functions.
The presence of the `shape_by` argument appears to cause `scale_fill_*()` to be ignored, with the default colour scale being used instead.

```
# this works
plotExpression(sce, features = my_genes, x = "cluster", colour_by = "cluster") +
    scale_fill_manual(name = "cluster", values = unname(pals::polychrome()))

# this does not work; scale_fill_manual() is ignored and the default colour scale is used
plotExpression(sce, features = my_genes, x = "cluster", colour_by = "cluster", shape_by = "condition") +
    scale_fill_manual(name = "cluster", values = unname(pals::polychrome()))
```

**Comment by alanocallaghan** [comment]
This is due to scater using fill instead of colour by default. However when using varying shapes, it reverts to colour. This behaviour is changed in the devel version; a workaround for now is to specify the desired aesthetics in the call to `scale_fill_*`, eg `scale_fill_manual(aesthetics =  c("fill", "colour"), name = "cluster", values = unname(pals::polychrome()))`

**Comment by ceiron61** [comment]
Thanks! Indeed, simply specifying `scale_colour_manual()` instead of `scale_fill_manual()` also works.
