### ISSUE TITLE
calculateQCMetrics() was depreciated. So how to obtain "is_feature_control" which automatically calcualted by calculateQCMetrics().

### ISSUE THREAD

**Issue by Anna-RNA88** [alanocallaghan/scater#145]
Hi Aaron, I am a fresh learner in scRNA-Seq analysis. I am following a tutorial from Sanger institute (from July 2019) on analysis of single cell RNA Seq data. In the tutorial, calculateQCMetrics was employed, which can automatically generate "is_feature_control" and stored in rowData for the following data overview and data visualization. Now because calculateQCMetrics() metrics function is depreciated, I would like to inquire how to generate the "is_feature_control" using other other package? 
Indeed, I try to use the quickPerCellQC() package to solved this problem. It works, which made me very happy. But still can not produce the picture that exactly the same as the tutorial. 
Could you provide some codes to help me figure out this problems. Thank you very much!
Anna

**Comment by LTLA** [comment]
There's a few historical points of discussion here.

In the beginning, we stored all features (endogenous genes and spike-in counts) together, in the same matrix. This was the motivation for `is_feature_control`, which was a logical vector indicating which of the rows were actually spike-in controls. Downstream functions could then use this vector to remove the spike-ins prior to, e.g., clustering or marker detection, as differences in spike-in coverage are usually not biologically interesting.

Over time, this ended up being a pain because every function had to remember to remove the spike-in counts prior to further analysis. It was too easy for developers to forget to do this and accidentally use the entire matrix. In addition, the submatrix formed by removing the spike-in features used up unnecessary memory, which is problematic for larger datasets.

So, to resolve this and to accommodate the increasing number of alternative features (e.g., CITE-seq, ATAC-seq, whatever), we added the concept of ["alternative Experiments"](http://bioconductor.org/books/3.13/OSCA.intro/the-singlecellexperiment-class.html#alternative-experiments) to the **SingleCellExperiment** package. This split up each set of features into their own separate matrices, allowing users to easily extract the desired subset of the data. For example, the "main Experiment" usually has the endogenous counts while the spike-ins are stored in an alternative Experiment; this means that developers of downstream functions don't need to worry about removing spike-ins because they've already been cut out into a separate object.

A side-effect of this decision was that there was no longer any need for an `is_feature_control` vector, because the endogenous and spike-in counts were held in different matrices. As such, this vector is no longer reported in any QC-related function - at least, none that I'm in charge of - because all of these functions assume that the controls have already been split off into alternative Experiments. Nonetheless, if you have all of your features in the same object, I suppose you could use the `rowSubset()` function to create this vector, e.g.,

```r
rowSubset(sce, "is_feature_control") <- feature_controls
rowData(sce)$is_feature_control
```

where `feature_controls` is a logical, integer or character vector specifying the rows of `sce` corresponding to feature controls.

You might also consider reading a more up-to-date tutorial at http://bioconductor.org/books/3.13/OSCA/.

**Comment by Anna-RNA88** [comment]
Hi Aaron, thanks a lot for your great and clear explanation, which help me better understand the SingleCellExperiment package. The books is very useful and amazing!! Many thanks for your kindness and help.
Cheers,
Anna

**Comment by Anna-RNA88** [comment]
Hi Aaron,

Just let you know that "feature_controls" is produced by calculateQCMetrics(). So I could not use the rowSubset() function. But this do not frustrate me to continue learning. 

I put the tutorial I am trying to follow for you to have a look:
     https://scrnaseq-course.cog.sanger.ac.uk/website/cleaning-the-expression-matrix.html#exprs-qc
I am wondering whether you can generate all the exactly same figures under the section of "7.3 Data visualization" that demonstrated by the tutorial. Grateful if you can have fun.

Best regards,
Anna

**Comment by LTLA** [comment]
Can I generate the same figures? Probably. 

Do I want to? Probably not. You're more than welcome to try, though.

**Comment by Anna-RNA88** [comment]
Okay. Well noted. Thank you very much, Aaron.
