### ISSUE TITLE
Option not to plot the points in violin plots

### ISSUE THREAD

**Issue by lambdamoses** [alanocallaghan/scater#174]
Is there an option not to plot all the points in violin plots in `plotColData()` and `plotExpression()`? When I set `point_size = 0`, the points are still plotted, though smaller than default. When there're say a few thousand cells and the number of cells per cluster is smaller, having the points help. However, when there're hundreds of thousands of cells, the points are not at all informative (except for outliers) since they all get overplotted into a solid color inside the violins, only to make plotting really slow. How to not plot the points in violin plots at all?

**Comment by alanocallaghan** [comment]
Try this on master:

```r
library("scater")
example_sce <- mockSCE()
example_sce <- logNormCounts(example_sce)
colData(example_sce) <- cbind(colData(example_sce), perCellQCMetrics(example_sce))
plotColData(example_sce, y = "detected", x = "Cell_Cycle", colour_by = "Mutation_Status", point_fun = function(...) list())
```

**Comment by lambdamoses** [comment]
Hi, thanks for fixing this. But it would still be nice to be able to fill the violins with colors to indicate clusters, as in Seurat. However, there's no `fill_by` argument. Also, I feel like `point_fun = function(...) list()` is kind of cumbersome and confusing to users who aren't very fluent in R. It would be nice to have an argument like `plot_points = FALSE`.

**Comment by alanocallaghan** [comment]
I don't know how common it is for people to not want points, and point_fun is a more flexible option than plot_points, so I'm going to leave it as is for now.

I'm slightly dubious about fill_by here as in the case that it's not the same as `x` you then have to start specifying positions and complexity may balloon slightly

**Comment by kikegoni** [comment]
Hey, 

First thanks a lot for developing and maintaining this package.

I agree that the ```fill_by``` argument would be also very good in these cases where you don't want to plot each individual point but just want to see the shape. I have seen that you have it in your code. The problem is that if I combine both options ```fill_by``` and ```point_fun = function(...) list()``` I have not been able to modify the colors of the violin plots and all my violins have the same color. 

```
plotColData(all_sce, x="ident",y="sum" ,point_fun = function(...) list(), fill_by = "ident")
```

Is there an option to just plot the shape of the violin and fill it according to your particular interest?

Thanks for any help you might be able to provide,

Kike

**Comment by alanocallaghan** [comment]
I'm going to open a separate issue (#175) as this is unrelated to the original topic.

Please submit any suggestions or feedback there instead
