### ISSUE TITLE
Have the default cell filters been removed?

### ISSUE THREAD

**Issue by wikiselev** [alanocallaghan/scater#26]
Look like there are no `filter_...` columns in `colData` slot anymore (for example, there used to be `filter_on_total_features` features). Have they been removed?

**Comment by LTLA** [comment]
Yes, because they were highly opaque. We felt it would be better for users to choose filter thresholds themselves, as this is often context-specific. It's not particularly difficult, and at least it is more obvious what is happening when someone reads the analysis report. Also, it reduces clutter in the output of `calculateQCMetrics`, which is probably a good thing given the amount of metadata it spews out.

**Comment by wikiselev** [comment]
Thanks, Aaron!
