### ISSUE TITLE
cell cycle regression and  Seurat object conversion

### ISSUE THREAD

**Issue by MichaelPeibo** [alanocallaghan/scater#50]
Hi Scater team,
I am currently trying different packages to cluster my 10x genomics data;
is scater able to regress out confounding factors such as cell cycle such as Seurat did in the ScaleData()?
Also, is scater able to directly convert SingleCellExperiment object to others such as Seurat or what Monocle2 did?
Thanks!

**Comment by LTLA** [comment]
There are well-established functions in Bioconductor for removing uninteresting effects of variation. `comBat` (in _sva_) and `removeBatchEffect` (in _limma_) come to mind. Alternatively, you could consider more advanced methods like the factor analysis model in _slalom_. Our philosophy is for users to pick their own methods for regressing out such factors, rather than re-inventing the wheel in _scater_. 

That being said, we used to have a `normaliseExprs` function that did scaling normalization, batch correction, etc. This will be deprecated in the next release, because I believe it is better for everyone if the individual functions are explicitly used in the analysis code. It's easier for users to write, as each function has one role and it's clear what is happening when you use it; it's easier for people to read your analysis report, for similar reasons; and it's easier for me as a developer, because I don't have to write a function that needs to cover every single possible combination of your use cases.

As for conversion between types; no, _scater_ does not have this, but `scran::convertTo` can convert to `DGEList` objects (for _edgeR_), `DESeqDataSet` (for _DESeq2_) and `CellDataSet` objects (for _monocle_).

**Comment by MichaelPeibo** [comment]
Hi, Aaron

Thanks for the help, I am trying slalom, which seems to be nice but a little challenge for me.
