### ISSUE TITLE
Adding Ensembl IDs for human data

### ISSUE THREAD

**Issue by MichaelPeibo** [alanocallaghan/scater#51]
Hi,
when I tried to add ENSEMBL ID for human cell data, I found there is some 'NA' for the output;

`# Adding Ensembl IDs.
library(EnsDb.Hsapiens.v75)
ensembl <- mapIds(EnsDb.Hsapiens.v75, keys=rownames(sce.qc.norm), keytype="SYMBOL",column=c("ENSEMBL"))
                 `

can anyone recommend which library should I use for mapping? I already tried some packages from AnnotationDbi, but I still get NA after mapping.

**Comment by LTLA** [comment]
This isn't a _scater_ question; post on the Bioconductor [support site](https://support.bioconductor.org) for more relevant answers.

If you want my two cents: unfortunately, some gene symbols don't exist in the annotation DBs, because everyone has a different name for their favourite gene. This is why I believe **all** high-throughput datasets should be generated and published using stable gene identifiers from Ensembl or Entrez (or something equivalent for your model system). People can always convert to their own gene symbols later.

**Comment by MichaelPeibo** [comment]
Thanks Aaron, it did not bother the cell cycle assignment actually.
