### ISSUE TITLE
plotRLE

### ISSUE THREAD

**Issue by ltosti** [alanocallaghan/scater#55]
I was trying to check the effect of normalisation by simply using:

`plotRLE(sce, list(Raw = "counts", Norm = "logcounts"), c(FALSE, TRUE), style = "minimal", order_by_colour = FALSE)`

But I get this error:

`Error in x[[i]] <- value : 
  attempt to select less than one element in OneIndex`

Any idea of what is causing this?

Thank you for your help.

**Comment by LTLA** [comment]
`plotRLE` is one of the few functions that escaped the major clean-up from the last release. In this case, the error is arising because the function actually always expects a `colour_by` argument - despite the documentation to the contrary! I will fix this, but for the time being, I suggest you just put in a `colour_by=`.

**Comment by LTLA** [comment]
I have modified `plotRLE` to avoid this bug. I have also changed it to avoid faceting, which makes the internals of the function unnecessarily complicated. So, in the next release (or if you install the Github version of _scater_), instead of using specifying a list of matrices, you can simply do:

```r
plotRLE(sce, exprs_values = "counts", exprs_logged=FALSE)
plotRLE(sce, exprs_values = "logcounts")
```

... to create two plots that you can arrange in any manner that you wish, e.g., using `multiplot`.

**Comment by ltosti** [comment]
Thank you @LTLA, I'll try to install the Github version!
