### ISSUE TITLE
show_smooth = TRUE not working in plotExpression

### ISSUE THREAD

**Issue by bruvellu** [alanocallaghan/scater#57]
Hi! After updating to v1.8.0 I noticed some of my plots were missing the fitted smooth. Is it broken?

```
library(scater)
data("sc_example_counts")
data("sc_example_cell_info")
example_sce <- SingleCellExperiment(
  assays = list(counts = sc_example_counts), 
  colData = sc_example_cell_info
)
example_sce <- calculateQCMetrics(example_sce)
plotExpression(example_sce, "Gene_1000", x = "Cell_Cycle", exprs_values = "counts",
               show_violin = FALSE, show_smooth = TRUE)
```
![lostsmooth](https://user-images.githubusercontent.com/361179/41728801-f5bf4f60-7577-11e8-91cf-c10f68683234.png)

Cheers

**Comment by LTLA** [comment]
It doesn't make much sense to create a smoothed line when your x-axis variable is categorical. If you read `?"scater-plot-args"` (as directed by the documentation for `...` in `?plotExpression`), you'll see that `show_smooth` only has an effect for scatter plots, i.e., when the x-axis is continuous. Indeed:

```r
plotExpression(example_sce, "Gene_1000", x = "Gene_1000", 
    exprs_values = "counts", show_smooth=TRUE)
```

... does as expected.

**Comment by bruvellu** [comment]
I see now! I didn't get that from the docs, specially because it worked before. But it makes sense.

I have time series data and that's why I would like the fitted smooth. I know it's not the best practice - and I do enjoy the violins a lot - but it's easier to see the progression with the fitted line.

![example](https://user-images.githubusercontent.com/361179/41738567-b41ff4ea-7592-11e8-86c9-5a1be05ef59a.png)

Can you suggest a workaround to add a fitted smooth line? I tried modifying the ggplot object using `geom_smooth`, but without success. Thanks!

**Comment by LTLA** [comment]
I don't actually work much with _ggplot_, so I don't really know. The corresponding code in _scater_ is:

```r
plot_out + stat_smooth(colour = "firebrick", linetype = 2, se = show_se)
```

... so that might work for you.

But this is a moot point. You seem pretty reasonable, so I'll give it to you straight. The "smoothed line" on the left plot is **craaazy**. I'll assume that the levels are in order, otherwise the line would clearly be nonsensical. Even so, to fit it, you need to assume that the distances between consecutive levels are quantitative (i.e., the distance from EGG to ABCD is the same as the distance from ABCD to CD). This seems difficult to justify, but if you can justify it, then you must have had enough information to create a proper scatter plot in the first place. Moreover, the jitter on the x-axis is randomly generated and does not actually correspond to any real data - if you try to fit a trend using those values, who knows what will come crawling out?

You say you have time-series data, so you must have some (numeric) times. This would make much more sense for plotting and trend fitting. Even if your times are imprecise and hand-wavy, it's better to make explicit assumptions about what you think the times are, in contrast to... whatever the left plot is doing.

**Comment by bruvellu** [comment]
Thanks for the input! I have numeric times (minutes) and can use it for plotting. They are equidistant, except for EGG-ABCD which is longer. But I'm using the plots to simply visually inspect the expression profiles from genes I got from DE downstream analyses, and not do any quantification. The smooth allows me to quickly check the trend, and still see the overall differences between replicates. The jittering is indeed troubling, I thought the trend was fitted on the underlying data and not on the actual jittered points. Perhaps I will just plot a line through the medians to get the same visual effect.

In any case, for some reason `geom_smooth`, `stat_smooth` or `stat_summary` do nothing in the example plot I posted above. They do work on your Gene vs Gene plot, though. I notice something similar when trying to modify the `geom_point` and `geom_violin` aesthetics from `plotExpression` and `plotReducedDim`, but that's probably some ggplot fiddling that I need to figure out.

**Comment by LTLA** [comment]
Now that you mention it, it may well be that the trend is fitted to the underlying data (i.e., the categorical values coerced into numbers via `factor`). But the jitter definitely doesn't _help_ the visualization - any casual inspection of the left plot will suggest that the trend was fitted using the x/y-coordinates of the points.

So yes, I think you would be better off (i) drawing connecting lines between medians for each time point and (ii) showing the violins to make clear that the jitter is not meaningful from trend fitting perspective.

Anyway, I'm closing this, as we have left _scater_ and gone into _ggplot_ territory.

**Comment by bruvellu** [comment]
Sure, thanks for the prompt feedback!
