### ISSUE TITLE
Input Consistency

### ISSUE THREAD

**Issue by DarioS** [alanocallaghan/scater#63]
A few functions allow a `SingleCellExperiment` object (e.g. `calculateCPM`) *or a count matrix* but the majority permit only a `SingleCellExperiment` (e.g. `calculateFPKM`). Are the few which accept a matrix remnants from the early days of the package and likely to be modified in a future version? `calculateCPM` and `calculateFPKM` perform a very similar task, so they ought to have consistent input formats.

**Comment by LTLA** [comment]
Is this still the case on the BioC-devel version? I thought I fixed this.

**Comment by DarioS** [comment]
Not any longer for those two functions, but some functions accept both a S4 container and a count matrix, whereas others only accept the S4 container (e.g. `plotTSNE`, `plotMDS`). Is there a rule of thumb to summarise which kinds of functions operate on which types of inputs?

**Comment by LTLA** [comment]
Well, ideally, none of the functions would accept a count matrix, and all of the functions would be limited to _SingleCellExperiment_ inputs. This is because we expect end-users to interact with SCE objects; indeed, the availability of metadata is essential for some plotting functions. Functions that accept matrix inputs do so mostly for historical reasons, or because it's convenient for certain developers (i.e., me) of other packages (i.e., _scran_) - these tend to be low-level calculations of expression values.

**Comment by DarioS** [comment]
Ah, of course. Boxing and unboxing of S4 container classes can be costly.
