### ISSUE TITLE
Can we follow semantic versioning on this package and be less aggressive with deprecation?

### ISSUE THREAD

**Issue by Shians** [alanocallaghan/scater#77]
I've noticed a few breaking changes and deprecation messages in the last release. I feel like this package could benefit from semantic versioning conventions: https://semver.org:

1. MAJOR version when you make incompatible API changes,
2. MINOR version when you add functionality in a backwards-compatible manner, and
3. PATCH version when you make backwards-compatible bug fixes.

Also I really don't see the benefit of deleting `normalise`, it's a trivial alias `normalise <- normalize` and removing it will break people's code. It's also inconsistent with the use of `colour` in the rest of the codebase. (Please don't take this as a request to change all instances of "colour" to "color")

**Comment by LTLA** [comment]
Minor version changes are dependent on BioC releases, so really there's only changes 1 and 3.  Bug and documentation fixes already go into 3. That leaves me with 1, which I would be bumping at every release cycle for the past 2 years, because that's how long it took to repair the package across all functions. I reckon we would be on _scater_ version 4 or 5 by now if I followed those guidelines.

The presence of `normalise` has disgusted me for a long time, and I am glad to be rid of it. Why anyone would use it instead of `normalize` is beyond me. The only thing stopping me from purging all uses of `colour_by` is my laziness, but now that you've pointed it out, I'll think about transitioning those to `color_by`. I think almost all code under my control follows American English, e.g., _BiocNeighbors_.

**Comment by jenzopr** [comment]
I get @Shians point and also yours, Aaron. My code relies on `scater` as well and was broken in some functionality with the `3.8` release. I'm sure you already thought about it - but what speaks against the usage of a `NEWS.md` file, as described e.g. [here](http://r-pkgs.had.co.nz/release.html#important-files)?

**Comment by LTLA** [comment]
We already have a `NEWS.Rd` file, which I've strived to keep up to date. You can see how many changes I made since we switched to a _SingleCellExperiment_. The good news is that the last of the breaking changes will hopefully be made in this release, namely getting rid of the _dplyr_-like verbs.

**Comment by jenzopr** [comment]
My bad, I looked for a `News` file in the top-level of the repository. But its great to see that you have it, thank you 😊

**Comment by LTLA** [comment]
As a general rule, I try to follow standard deprecation procedures. But as you might tell from the extent of the changes in `NEWS.Rd`, it's hard to be concerned about the paint job when the engine needs replacing. Indeed, if there was a time for a major version bump, it would have happened in the transition to SCE (see the glib one-liner in the NEWS). It didn't happen then and it's too late now.
