### ISSUE TITLE
plotPCASCE option inconsistency

### ISSUE THREAD

**Issue by fumi-github** [alanocallaghan/scater#82]
When using plotPCASCE (and presumably also plotPCA), the option exprs_values causes and error, and the option by_exprs_values is not effective.  It seems that plotPCASCE calls two functions, runPCA and plotReducedDim.  The former function takes the option exprs_values and the latter function takes the option by_exprs_values.  The inconsistency appears to be causing the problem.
I am using scater_1.10.1 in R version 3.5.2 (2018-12-20).
Last but not least, thank you for your wonderful program!

**Comment by LTLA** [comment]
I assume you didn't read the documentation, as this would have answered your questions.

As you have already surmised, `plotPCASCE` calls `plotReducedDim` to make the plot, which has a `by_exprs_values` argument. Let's have a look at how this argument is documented:

> by_exprs_values: A string or integer scalar specifying which assay to obtain expression values from, for use in point aesthetics - see `?"scater-vis-var"` for details.

So, setting `by_exprs_values` will **only** change the aesthetic appearance of the plot points in terms of the colour or size scale. It will **not** change the computed position of the points.

If you read `?plotPCASCE` further, it tells you that:

> Each function will search the `reducedDims` slot for an appropriately named set of results and pass those coordinates `plotReducedDim`. If the results are not present or `rerun=TRUE`, they will be computed using the relevant `run*` function. 

I'll assume you don't already have PCA results in your `SingleCellExperiment`. If that's the case, the documentation above tells us that `plotPCASCE` will compute the PCA using `runPCA`. What happens if you want to change the arguments used by `runPCA`? Well, again, if you read the documentation:

> run_args: Arguments to pass to `runPCA`, `runTSNE`, etc.

Thus, if you want to change the assay that is used for PCA, you should be doing:

```r
plotPCA(sce, run_args=list(exprs_values="my_new_values"))
```

No inconsistencies involved.

**Comment by fumi-github** [comment]
Thank you for the clarification.
I was missing the run_args part.
My apologies for taking your time.
