### ISSUE TITLE
getBMFeatureAnnos

### ISSUE THREAD

**Issue by annajbott** [alanocallaghan/scater#89]
getBMFeatureAnnos works fine for a small subset of my sce however when I try and use it for my whole dataset I get this error:

_Error in biomaRt::getBM(attributes = attributes, filters = filters, values = ids, : The query to the BioMart webservice returned an invalid result: biomaRt expected a character string of length 1. Please report this on the support site at http://support.bioconductor.org / Please report this to the mailing list_

Which is a biomaRt problem , however some people are saying this can be fixed by specifying the mart to use and using ensemblRedirect =FALSE
_mart <-biomaRt::useMart(biomart = "ENSEMBL_MART_ENSEMBL", 
              dataset = ensembl_data, 
              host = "www.ensembl.org",
              ensemblRedirect = FALSE)
sce <- biomaRt::getBM(sce, filters = "ensembl_gene_id", attributes = c("ensembl_gene_id", symbol, "chromosome_name"), mart = mart)_

However this is not possible using getBMFeatureAnnos.
Any ideas? I quite like this function as it should give gene symbols (more intuitive than ensembl IDs) as well as chromosome names which I can then use to select mitochondrial genes and set as feature controls.

**Comment by LTLA** [comment]
I guess it couldn't hurt.

**Comment by lucygarner** [comment]
Hi @annajbott and @LTLA,

I am getting the same error with getBMFeatureAnnos.  Were you able to resolve this in the end?

Best wishes,
Lucy

**Comment by LTLA** [comment]
The `getBMFeatureAnnos` function in BioC-devel _scater_ (imminent release this Friday) allows extra arguments to `biomaRt::useMart` to be passed in via the `...` argument.

I should mention that the BioMart servers themselves have been fickle recently (not the _biomaRt_ package; I'm talking about the actual underlying service provided by the EBI). There appear to be some questions about the long-term support for this resource - @grimbough would know more.

So, I have been pushing the use of AnnotationHub instead for annotation, see for example [here](https://osca.bioconductor.org/quality-control.html#choice-of-qc-metrics). The great thing about AnnotationHub is that it downloads once and caches the result, which is faster and more reliable; you never have to worry about your script failing because BioMart was down.

**Comment by lucygarner** [comment]
Great thanks Aaron.  AnnotationHub sounds like it might be a good way to go.
